/**
 * Duck: ResourceQuota
 * constants: resourceQuota
 *
 */
export const prefix = 'resourceQuota';

/**
 *  constants
 */
export const LOAD_RESOURCE_QUOTA = `${prefix}/LOAD_RESOURCE_QUOTA`;
export const LOAD_RESOURCE_QUOTA_SUCCESS = `${prefix}/LOAD_RESOURCE_QUOTA_SUCCESS`;
export const LOAD_RESOURCE_QUOTA_FAILURE = `${prefix}/LOAD_RESOURCE_QUOTA_FAILURE`;

export const CREATE_RESOURCE_QUOTUM = `${prefix}/CREATE_RESOURCE_QUOTUM`;
export const CREATE_RESOURCE_QUOTUM_SUCCESS = `${prefix}/CREATE_RESOURCE_QUOTUM_SUCCESS`;
export const CREATE_RESOURCE_QUOTUM_FAILURE = `${prefix}/CREATE_RESOURCE_QUOTUM_FAILURE`;

export const READ_RESOURCE_QUOTUM = `${prefix}/READ_RESOURCE_QUOTUM`;
export const READ_RESOURCE_QUOTUM_SUCCESS = `${prefix}/READ_RESOURCE_QUOTUM_SUCCESS`;
export const READ_RESOURCE_QUOTUM_FAILURE = `${prefix}/READ_RESOURCE_QUOTUM_FAILURE`;

export const REMOVE_RESOURCE_QUOTUM = `${prefix}/REMOVE_RESOURCE_QUOTUM`;
export const REMOVE_RESOURCE_QUOTUM_SUCCESS = `${prefix}/REMOVE_RESOURCE_QUOTUM_SUCCESS`;
export const REMOVE_RESOURCE_QUOTUM_FAILURE = `${prefix}/REMOVE_RESOURCE_QUOTUM_FAILURE`;

export const CLEAR_ERRORS_LIST = `${prefix}/CLEAR_ERRORS_LIST`;
