/**
 * Duck: Horizontalpodautoscalers
 * constants: horizontalpodautoscalers
 *
 */
export const prefix = 'horizontalpodautoscalers';

/**
 *  constants
 */
export const LOAD_HORIZONTALPODAUTOSCALERS = `${prefix}/LOAD_HORIZONTALPODAUTOSCALERS`;
export const LOAD_HORIZONTALPODAUTOSCALERS_SUCCESS = `${prefix}/LOAD_HORIZONTALPODAUTOSCALERS_SUCCESS`;
export const LOAD_HORIZONTALPODAUTOSCALERS_FAILURE = `${prefix}/LOAD_HORIZONTALPODAUTOSCALERS_FAILURE`;

export const CREATE_HORIZONTALPODAUTOSCALER = `${prefix}/CREATE_HORIZONTALPODAUTOSCALER`;
export const CREATE_HORIZONTALPODAUTOSCALER_SUCCESS = `${prefix}/CREATE_HORIZONTALPODAUTOSCALER_SUCCESS`;
export const CREATE_HORIZONTALPODAUTOSCALER_FAILURE = `${prefix}/CREATE_HORIZONTALPODAUTOSCALER_FAILURE`;

export const UPDATE_HORIZONTALPODAUTOSCALER = `${prefix}/UPDATE_HORIZONTALPODAUTOSCALER`;
export const UPDATE_HORIZONTALPODAUTOSCALER_SUCCESS = `${prefix}/UPDATE_HORIZONTALPODAUTOSCALER_SUCCESS`;
export const UPDATE_HORIZONTALPODAUTOSCALER_FAILURE = `${prefix}/UPDATE_HORIZONTALPODAUTOSCALER_FAILURE`;

export const READ_HORIZONTALPODAUTOSCALER = `${prefix}/READ_HORIZONTALPODAUTOSCALER`;
export const READ_HORIZONTALPODAUTOSCALER_SUCCESS = `${prefix}/READ_HORIZONTALPODAUTOSCALER_SUCCESS`;
export const READ_HORIZONTALPODAUTOSCALER_FAILURE = `${prefix}/READ_HORIZONTALPODAUTOSCALER_FAILURE`;

export const REMOVE_HORIZONTALPODAUTOSCALER = `${prefix}/REMOVE_HORIZONTALPODAUTOSCALER`;
export const REMOVE_HORIZONTALPODAUTOSCALER_SUCCESS = `${prefix}/REMOVE_HORIZONTALPODAUTOSCALER_SUCCESS`;
export const REMOVE_HORIZONTALPODAUTOSCALER_FAILURE = `${prefix}/REMOVE_HORIZONTALPODAUTOSCALER_FAILURE`;

export const CLEAR_ERRORS_LIST = `${prefix}/CLEAR_ERRORS_LIST`;
