/**
 * Duck: HorizontalPodAutoscalers
 * constants: horizontalPodAutoscalers
 *
 */
export const prefix = 'horizontalPodAutoscalers';

/**
 *  constants
 */
export const LOAD_HORIZONTAL_POD_AUTOSCALERS = `${prefix}/LOAD_HORIZONTAL_POD_AUTOSCALERS`;
export const LOAD_HORIZONTAL_POD_AUTOSCALERS_SUCCESS = `${prefix}/LOAD_HORIZONTAL_POD_AUTOSCALERS_SUCCESS`;
export const LOAD_HORIZONTAL_POD_AUTOSCALERS_FAILURE = `${prefix}/LOAD_HORIZONTAL_POD_AUTOSCALERS_FAILURE`;

export const CREATE_HORIZONTAL_POD_AUTOSCALER = `${prefix}/CREATE_HORIZONTAL_POD_AUTOSCALER`;
export const CREATE_HORIZONTAL_POD_AUTOSCALER_SUCCESS = `${prefix}/CREATE_HORIZONTAL_POD_AUTOSCALER_SUCCESS`;
export const CREATE_HORIZONTAL_POD_AUTOSCALER_FAILURE = `${prefix}/CREATE_HORIZONTAL_POD_AUTOSCALER_FAILURE`;

export const UPDATE_HORIZONTAL_POD_AUTOSCALER = `${prefix}/UPDATE_HORIZONTAL_POD_AUTOSCALER`;
export const UPDATE_HORIZONTAL_POD_AUTOSCALER_SUCCESS = `${prefix}/UPDATE_HORIZONTAL_POD_AUTOSCALER_SUCCESS`;
export const UPDATE_HORIZONTAL_POD_AUTOSCALER_FAILURE = `${prefix}/UPDATE_HORIZONTAL_POD_AUTOSCALER_FAILURE`;

export const READ_HORIZONTAL_POD_AUTOSCALER = `${prefix}/READ_HORIZONTAL_POD_AUTOSCALER`;
export const READ_HORIZONTAL_POD_AUTOSCALER_SUCCESS = `${prefix}/READ_HORIZONTAL_POD_AUTOSCALER_SUCCESS`;
export const READ_HORIZONTAL_POD_AUTOSCALER_FAILURE = `${prefix}/READ_HORIZONTAL_POD_AUTOSCALER_FAILURE`;

export const REMOVE_HORIZONTAL_POD_AUTOSCALER = `${prefix}/REMOVE_HORIZONTAL_POD_AUTOSCALER`;
export const REMOVE_HORIZONTAL_POD_AUTOSCALER_SUCCESS = `${prefix}/REMOVE_HORIZONTAL_POD_AUTOSCALER_SUCCESS`;
export const REMOVE_HORIZONTAL_POD_AUTOSCALER_FAILURE = `${prefix}/REMOVE_HORIZONTAL_POD_AUTOSCALER_FAILURE`;

export const CLEAR_ERRORS_LIST = `${prefix}/CLEAR_ERRORS_LIST`;
