export const prefix = 'statefulSets';
/*
  constants
*/
export const LOAD_STATEFULSETS = `${prefix}/LOAD_STATEFULSETS`;
export const LOAD_STATEFULSETS_SUCCESS = `${prefix}/LOAD_STATEFULSETS_SUCCESS`;
export const LOAD_STATEFULSETS_FAILURE = `${prefix}/LOAD_STATEFULSETS_FAILURE`;

export const LOAD_STATEFULSET = `${prefix}/LOAD_STATEFULSET`;
export const LOAD_STATEFULSET_SUCCESS = `${prefix}/LOAD_STATEFULSET_SUCCESS`;
export const LOAD_STATEFULSET_FAILURE = `${prefix}/LOAD_STATEFULSET_FAILURE`;

export const CREATE_STATEFULSET = `${prefix}/CREATE_STATEFULSET`;
export const CREATE_STATEFULSET_SUCCESS = `${prefix}/CREATE_STATEFULSET_SUCCESS`;
export const CREATE_STATEFULSET_FAILURE = `${prefix}/CREATE_STATEFULSET_FAILURE`;

export const UPDATE_STATEFULSET = `${prefix}/UPDATE_STATEFULSET`;
export const UPDATE_STATEFULSET_SUCCESS = `${prefix}/UPDATE_STATEFULSET_SUCCESS`;
export const UPDATE_STATEFULSET_FAILURE = `${prefix}/UPDATE_STATEFULSET_FAILURE`;

export const REMOVE_STATEFULSET = `${prefix}/REMOVE_STATEFULSET`;
export const REMOVE_STATEFULSET_SUCCESS = `${prefix}/REMOVE_STATEFULSET_SUCCESS`;
export const REMOVE_STATEFULSET_FAILURE = `${prefix}/REMOVE_STATEFULSET_FAILURE`;

export const RESET_PASSWORD = `${prefix}/RESET_PASSWORD`;
export const RESET_PASSWORD_SUCCESS = `${prefix}/RESET_PASSWORD_SUCCESS`;
export const RESET_PASSWORD_FAILURE = `${prefix}/RESET_PASSWORD_FAILURE`;

export const SCALE_STATEFULSET = `${prefix}/SCALE_STATEFULSET`;
export const SCALE_STATEFULSET_SUCCESS = `${prefix}/SCALE_STATEFULSET_SUCCESS`;
export const SCALE_STATEFULSET_FAILURE = `${prefix}/SCALE_STATEFULSET_FAILURE`;
