/**
 * Duck: StatefulSets
 * constants: statefulSets
 *
 */
export const prefix = 'statefulSets';

/**
 *  constants
 */
export const LOAD_STATEFUL_SETS = `${prefix}/LOAD_STATEFUL_SETS`;
export const LOAD_STATEFUL_SETS_SUCCESS = `${prefix}/LOAD_STATEFUL_SETS_SUCCESS`;
export const LOAD_STATEFUL_SETS_FAILURE = `${prefix}/LOAD_STATEFUL_SETS_FAILURE`;

export const CREATE_STATEFUL_SET = `${prefix}/CREATE_STATEFUL_SET`;
export const CREATE_STATEFUL_SET_SUCCESS = `${prefix}/CREATE_STATEFUL_SET_SUCCESS`;
export const CREATE_STATEFUL_SET_FAILURE = `${prefix}/CREATE_STATEFUL_SET_FAILURE`;

export const UPDATE_STATEFUL_SET = `${prefix}/UPDATE_STATEFUL_SET`;
export const UPDATE_STATEFUL_SET_SUCCESS = `${prefix}/UPDATE_STATEFUL_SET_SUCCESS`;
export const UPDATE_STATEFUL_SET_FAILURE = `${prefix}/UPDATE_STATEFUL_SET_FAILURE`;

export const READ_STATEFUL_SET = `${prefix}/READ_STATEFUL_SET`;
export const READ_STATEFUL_SET_SUCCESS = `${prefix}/READ_STATEFUL_SET_SUCCESS`;
export const READ_STATEFUL_SET_FAILURE = `${prefix}/READ_STATEFUL_SET_FAILURE`;

export const REMOVE_STATEFUL_SET = `${prefix}/REMOVE_STATEFUL_SET`;
export const REMOVE_STATEFUL_SET_SUCCESS = `${prefix}/REMOVE_STATEFUL_SET_SUCCESS`;
export const REMOVE_STATEFUL_SET_FAILURE = `${prefix}/REMOVE_STATEFUL_SET_FAILURE`;

export const EXECUTE_STATEFUL_SET_ACTION = `${prefix}/EXECUTE_STATEFUL_SET_ACTION`;
export const EXECUTE_STATEFUL_SET_ACTION_SUCCESS = `${prefix}/EXECUTE_STATEFUL_SET_ACTION_SUCCESS`;
export const EXECUTE_STATEFUL_SET_ACTION_FAILURE = `${prefix}/EXECUTE_STATEFUL_SET_ACTION_FAILURE`;

export const CLEAR_ERRORS_LIST = `${prefix}/CLEAR_ERRORS_LIST`;
