export const prefix = 'applications';

/**
 *  constants
 */
export const LOAD_APPLICATIONS = `${prefix}/LOAD_APPLICATIONS`;
export const LOAD_APPLICATIONS_SUCCESS = `${prefix}/LOAD_APPLICATIONS_SUCCESS`;
export const LOAD_APPLICATIONS_FAILURE = `${prefix}/LOAD_APPLICATIONS_FAILURE`;

export const LOAD_CHART = `${prefix}/LOAD_CHART`;
export const LOAD_CHART_SUCCESS = `${prefix}/LOAD_CHART_SUCCESS`;
export const LOAD_CHART_FAILURE = `${prefix}/LOAD_CHART_FAILURE`;

export const CREATE_APPLICATION = `${prefix}/CREATE_APPLICATION`;
export const CREATE_APPLICATION_SUCCESS = `${prefix}/CREATE_APPLICATION_SUCCESS`;
export const CREATE_APPLICATION_FAILURE = `${prefix}/CREATE_APPLICATION_FAILURE`;

export const REMOVE_APPLICATION = `${prefix}/REMOVE_APPLICATION`;
export const REMOVE_APPLICATION_SUCCESS = `${prefix}/REMOVE_APPLICATION_SUCCESS`;
export const REMOVE_APPLICATION_FAILURE = `${prefix}/REMOVE_APPLICATION_FAILURE`;

export const CHANGE_APPLICATION = `${prefix}/CHANGE_APPLICATION`;

export const CLEAR_DELETE_ERROR_INFO = `${prefix}/CLEAR_DELETE_ERROR_INFO`;

