/**
 * Duck: PersistentVolumes
 * constants: persistentVolumes
 *
 */
export const prefix = 'persistentVolumes';

/**
 *  constants
 */
export const LOAD_PERSISTENT_VOLUMES = `${prefix}/LOAD_PERSISTENT_VOLUMES`;
export const LOAD_PERSISTENT_VOLUMES_SUCCESS = `${prefix}/LOAD_PERSISTENT_VOLUMES_SUCCESS`;
export const LOAD_PERSISTENT_VOLUMES_FAILURE = `${prefix}/LOAD_PERSISTENT_VOLUMES_FAILURE`;

export const READ_PERSISTENT_VOLUME = `${prefix}/READ_PERSISTENT_VOLUME`;
export const READ_PERSISTENT_VOLUME_SUCCESS = `${prefix}/READ_PERSISTENT_VOLUME_SUCCESS`;
export const READ_PERSISTENT_VOLUME_FAILURE = `${prefix}/READ_PERSISTENT_VOLUME_FAILURE`;

export const REMOVE_PERSISTENT_VOLUME = `${prefix}/REMOVE_PERSISTENT_VOLUME`;
export const REMOVE_PERSISTENT_VOLUME_SUCCESS = `${prefix}/REMOVE_PERSISTENT_VOLUME_SUCCESS`;
export const REMOVE_PERSISTENT_VOLUME_FAILURE = `${prefix}/REMOVE_PERSISTENT_VOLUME_FAILURE`;

export const CLEAR_ERRORS_LIST = `${prefix}/CLEAR_ERRORS_LIST`;
