/**
 * Duck: Fluentbitconfigs
 * constants: fluentbitconfigs
 *
 */
export const prefix = 'fluentbitconfigs';

/**
 *  constants
 */
export const LOAD_FLUENTBITCONFIGS = `${prefix}/LOAD_FLUENTBITCONFIGS`;
export const LOAD_FLUENTBITCONFIGS_SUCCESS = `${prefix}/LOAD_FLUENTBITCONFIGS_SUCCESS`;
export const LOAD_FLUENTBITCONFIGS_FAILURE = `${prefix}/LOAD_FLUENTBITCONFIGS_FAILURE`;

export const CREATE_FLUENTBITCONFIG = `${prefix}/CREATE_FLUENTBITCONFIG`;
export const CREATE_FLUENTBITCONFIG_SUCCESS = `${prefix}/CREATE_FLUENTBITCONFIG_SUCCESS`;
export const CREATE_FLUENTBITCONFIG_FAILURE = `${prefix}/CREATE_FLUENTBITCONFIG_FAILURE`;

export const UPDATE_FLUENTBITCONFIG = `${prefix}/UPDATE_FLUENTBITCONFIG`;
export const UPDATE_FLUENTBITCONFIG_SUCCESS = `${prefix}/UPDATE_FLUENTBITCONFIG_SUCCESS`;
export const UPDATE_FLUENTBITCONFIG_FAILURE = `${prefix}/UPDATE_FLUENTBITCONFIG_FAILURE`;

export const READ_FLUENTBITCONFIG = `${prefix}/READ_FLUENTBITCONFIG`;
export const READ_FLUENTBITCONFIG_SUCCESS = `${prefix}/READ_FLUENTBITCONFIG_SUCCESS`;
export const READ_FLUENTBITCONFIG_FAILURE = `${prefix}/READ_FLUENTBITCONFIG_FAILURE`;

export const REMOVE_FLUENTBITCONFIG = `${prefix}/REMOVE_FLUENTBITCONFIG`;
export const REMOVE_FLUENTBITCONFIG_SUCCESS = `${prefix}/REMOVE_FLUENTBITCONFIG_SUCCESS`;
export const REMOVE_FLUENTBITCONFIG_FAILURE = `${prefix}/REMOVE_FLUENTBITCONFIG_FAILURE`;

export const CLEAR_ERRORS_LIST = `${prefix}/CLEAR_ERRORS_LIST`;
