/*
 *
 * ApplicationsPage constants
 *
 */
const prefix = 'app/ApplicationsPage';

export const INIT_ACTION = `${prefix}/INIT_ACTION`;

export const LOAD_APPLICATIONS = `${prefix}/LOAD_APPLICATIONS`;
export const LOAD_APPLICATIONS_REQUEST = `${prefix}/LOAD_APPLICATIONS_REQUEST`;
export const LOAD_APPLICATIONS_SUCCESS = `${prefix}/LOAD_APPLICATIONS_SUCCESS`;
export const LOAD_APPLICATIONS_FAILURE = `${prefix}/LOAD_APPLICATIONS_FAILURE`;

export const INIT_CREATE_FORM = `${prefix}/INIT_CREATE_FORM`;

export const CREATE_APPLICATION = `${prefix}/CREATE_APPLICATION`;
export const CREATE_APPLICATION_REQUEST = `${prefix}/CREATE_APPLICATION_REQUEST`;
export const CREATE_APPLICATION_SUCCESS = `${prefix}/CREATE_APPLICATION_SUCCESS`;
export const CREATE_APPLICATION_FAILURE = `${prefix}/CREATE_APPLICATION_FAILURE`;

export const UPDATE_CREATE_FORM = `${prefix}/UPDATE_CREATE_FORM`;

export const REMOVE_APPLICATION = `${prefix}/REMOVE_APPLICATION`;
export const REMOVE_APPLICATION_REQUEST = `${prefix}/REMOVE_APPLICATION_REQUEST`;
export const REMOVE_APPLICATION_SUCCESS = `${prefix}/REMOVE_APPLICATION_SUCCESS`;
export const REMOVE_APPLICATION_FAILURE = `${prefix}/REMOVE_APPLICATION_FAILURE`;
