export const prefix = 'deployments';
/*
  constants
*/
export const LOAD_DEPLOYMENTS = `${prefix}/LOAD_DEPLOYMENTS`;
export const LOAD_DEPLOYMENTS_SUCCESS = `${prefix}/LOAD_DEPLOYMENTS_SUCCESS`;
export const LOAD_DEPLOYMENTS_FAILURE = `${prefix}/LOAD_DEPLOYMENTS_FAILURE`;

export const LOAD_DEPLOYMENT = `${prefix}/LOAD_DEPLOYMENT`;
export const LOAD_DEPLOYMENT_SUCCESS = `${prefix}/LOAD_DEPLOYMENT_SUCCESS`;
export const LOAD_DEPLOYMENT_FAILURE = `${prefix}/LOAD_DEPLOYMENT_FAILURE`;

export const CREATE_DEPLOYMENT = `${prefix}/CREATE_DEPLOYMENT`;
export const CREATE_DEPLOYMENT_SUCCESS = `${prefix}/CREATE_DEPLOYMENT_SUCCESS`;
export const CREATE_DEPLOYMENT_FAILURE = `${prefix}/CREATE_DEPLOYMENT_FAILURE`;

export const UPDATE_DEPLOYMENT = `${prefix}/UPDATE_DEPLOYMENT`;
export const UPDATE_DEPLOYMENT_SUCCESS = `${prefix}/UPDATE_DEPLOYMENT_SUCCESS`;
export const UPDATE_DEPLOYMENT_FAILURE = `${prefix}/UPDATE_DEPLOYMENT_FAILURE`;

export const REMOVE_DEPLOYMENT = `${prefix}/REMOVE_DEPLOYMENT`;
export const REMOVE_DEPLOYMENT_SUCCESS = `${prefix}/REMOVE_DEPLOYMENT_SUCCESS`;
export const REMOVE_DEPLOYMENT_FAILURE = `${prefix}/REMOVE_DEPLOYMENT_FAILURE`;

export const SCALE_DEPLOYMENT = `${prefix}/SCALE_DEPLOYMENT`;
export const SCALE_DEPLOYMENT_SUCCESS = `${prefix}/SCALE_DEPLOYMENT_SUCCESS`;
export const SCALE_DEPLOYMENT_FAILURE = `${prefix}/SCALE_DEPLOYMENT_FAILURE`;
