/**
 * Duck: Deployments
 * constants: deployments
 *
 */
export const prefix = 'deployments';

/**
 *  constants
 */
export const LOAD_DEPLOYMENTS = `${prefix}/LOAD_DEPLOYMENTS`;
export const LOAD_DEPLOYMENTS_SUCCESS = `${prefix}/LOAD_DEPLOYMENTS_SUCCESS`;
export const LOAD_DEPLOYMENTS_FAILURE = `${prefix}/LOAD_DEPLOYMENTS_FAILURE`;

export const CREATE_DEPLOYMENT = `${prefix}/CREATE_DEPLOYMENT`;
export const CREATE_DEPLOYMENT_SUCCESS = `${prefix}/CREATE_DEPLOYMENT_SUCCESS`;
export const CREATE_DEPLOYMENT_FAILURE = `${prefix}/CREATE_DEPLOYMENT_FAILURE`;

export const UPDATE_DEPLOYMENT = `${prefix}/UPDATE_DEPLOYMENT`;
export const UPDATE_DEPLOYMENT_SUCCESS = `${prefix}/UPDATE_DEPLOYMENT_SUCCESS`;
export const UPDATE_DEPLOYMENT_FAILURE = `${prefix}/UPDATE_DEPLOYMENT_FAILURE`;

export const READ_DEPLOYMENT = `${prefix}/READ_DEPLOYMENT`;
export const READ_DEPLOYMENT_SUCCESS = `${prefix}/READ_DEPLOYMENT_SUCCESS`;
export const READ_DEPLOYMENT_FAILURE = `${prefix}/READ_DEPLOYMENT_FAILURE`;

export const REMOVE_DEPLOYMENT = `${prefix}/REMOVE_DEPLOYMENT`;
export const REMOVE_DEPLOYMENT_SUCCESS = `${prefix}/REMOVE_DEPLOYMENT_SUCCESS`;
export const REMOVE_DEPLOYMENT_FAILURE = `${prefix}/REMOVE_DEPLOYMENT_FAILURE`;

export const EXECUTE_DEPLOYMENT_ACTION = `${prefix}/EXECUTE_DEPLOYMENT_ACTION`;
export const EXECUTE_DEPLOYMENT_ACTION_SUCCESS = `${prefix}/EXECUTE_DEPLOYMENT_ACTION_SUCCESS`;
export const EXECUTE_DEPLOYMENT_ACTION_FAILURE = `${prefix}/EXECUTE_DEPLOYMENT_ACTION_FAILURE`;

export const CLEAR_ERRORS_LIST = `${prefix}/CLEAR_ERRORS_LIST`;
