/**
 * Duck: StorageClusters
 * constants: storageClusters
 *
 */
export const prefix = 'storageClusters';

/**
 *  constants
 */
export const LOAD_STORAGE_CLUSTERS = `${prefix}/LOAD_STORAGE_CLUSTERS`;
export const LOAD_STORAGE_CLUSTERS_SUCCESS = `${prefix}/LOAD_STORAGE_CLUSTERS_SUCCESS`;
export const LOAD_STORAGE_CLUSTERS_FAILURE = `${prefix}/LOAD_STORAGE_CLUSTERS_FAILURE`;

export const CREATE_STORAGE_CLUSTER = `${prefix}/CREATE_STORAGE_CLUSTER`;
export const CREATE_STORAGE_CLUSTER_SUCCESS = `${prefix}/CREATE_STORAGE_CLUSTER_SUCCESS`;
export const CREATE_STORAGE_CLUSTER_FAILURE = `${prefix}/CREATE_STORAGE_CLUSTER_FAILURE`;

export const UPDATE_STORAGE_CLUSTER = `${prefix}/UPDATE_STORAGE_CLUSTER`;
export const UPDATE_STORAGE_CLUSTER_SUCCESS = `${prefix}/UPDATE_STORAGE_CLUSTER_SUCCESS`;
export const UPDATE_STORAGE_CLUSTER_FAILURE = `${prefix}/UPDATE_STORAGE_CLUSTER_FAILURE`;

export const READ_STORAGE_CLUSTER = `${prefix}/READ_STORAGE_CLUSTER`;
export const READ_STORAGE_CLUSTER_SUCCESS = `${prefix}/READ_STORAGE_CLUSTER_SUCCESS`;
export const READ_STORAGE_CLUSTER_FAILURE = `${prefix}/READ_STORAGE_CLUSTER_FAILURE`;

export const REMOVE_STORAGE_CLUSTER = `${prefix}/REMOVE_STORAGE_CLUSTER`;
export const REMOVE_STORAGE_CLUSTER_SUCCESS = `${prefix}/REMOVE_STORAGE_CLUSTER_SUCCESS`;
export const REMOVE_STORAGE_CLUSTER_FAILURE = `${prefix}/REMOVE_STORAGE_CLUSTER_FAILURE`;
