/**
 * Duck: PersistentVolumeClaims
 * constants: persistentVolumeClaims
 *
 */
export const prefix = 'persistentVolumeClaims';

/**
 *  constants
 */
export const LOAD_PERSISTENT_VOLUME_CLAIMS = `${prefix}/LOAD_PERSISTENT_VOLUME_CLAIMS`;
export const LOAD_PERSISTENT_VOLUME_CLAIMS_SUCCESS = `${prefix}/LOAD_PERSISTENT_VOLUME_CLAIMS_SUCCESS`;
export const LOAD_PERSISTENT_VOLUME_CLAIMS_FAILURE = `${prefix}/LOAD_PERSISTENT_VOLUME_CLAIMS_FAILURE`;

export const REMOVE_PERSISTENT_VOLUME_CLAIM = `${prefix}/REMOVE_PERSISTENT_VOLUME_CLAIM`;
export const REMOVE_PERSISTENT_VOLUME_CLAIM_SUCCESS = `${prefix}/REMOVE_PERSISTENT_VOLUME_CLAIM_SUCCESS`;
export const REMOVE_PERSISTENT_VOLUME_CLAIM_FAILURE = `${prefix}/REMOVE_PERSISTENT_VOLUME_CLAIM_FAILURE`;

export const CLEAR_ERRORS_LIST = `${prefix}/CLEAR_ERRORS_LIST`;
