/**
 * Duck: NamespaceThresholds
 * constants: namespaceThresholds
 *
 */
export const prefix = 'namespaceThresholds';

/**
 *  constants
 */
export const LOAD_NAMESPACE_THRESHOLDS = `${prefix}/LOAD_NAMESPACE_THRESHOLDS`;
export const LOAD_NAMESPACE_THRESHOLDS_SUCCESS = `${prefix}/LOAD_NAMESPACE_THRESHOLDS_SUCCESS`;
export const LOAD_NAMESPACE_THRESHOLDS_FAILURE = `${prefix}/LOAD_NAMESPACE_THRESHOLDS_FAILURE`;

export const CREATE_NAMESPACE_THRESHOLD = `${prefix}/CREATE_NAMESPACE_THRESHOLD`;
export const CREATE_NAMESPACE_THRESHOLD_SUCCESS = `${prefix}/CREATE_NAMESPACE_THRESHOLD_SUCCESS`;
export const CREATE_NAMESPACE_THRESHOLD_FAILURE = `${prefix}/CREATE_NAMESPACE_THRESHOLD_FAILURE`;

export const UPDATE_NAMESPACE_THRESHOLD = `${prefix}/UPDATE_NAMESPACE_THRESHOLD`;
export const UPDATE_NAMESPACE_THRESHOLD_SUCCESS = `${prefix}/UPDATE_NAMESPACE_THRESHOLD_SUCCESS`;
export const UPDATE_NAMESPACE_THRESHOLD_FAILURE = `${prefix}/UPDATE_NAMESPACE_THRESHOLD_FAILURE`;

export const READ_NAMESPACE_THRESHOLD = `${prefix}/READ_NAMESPACE_THRESHOLD`;
export const READ_NAMESPACE_THRESHOLD_SUCCESS = `${prefix}/READ_NAMESPACE_THRESHOLD_SUCCESS`;
export const READ_NAMESPACE_THRESHOLD_FAILURE = `${prefix}/READ_NAMESPACE_THRESHOLD_FAILURE`;

export const REMOVE_NAMESPACE_THRESHOLD = `${prefix}/REMOVE_NAMESPACE_THRESHOLD`;
export const REMOVE_NAMESPACE_THRESHOLD_SUCCESS = `${prefix}/REMOVE_NAMESPACE_THRESHOLD_SUCCESS`;
export const REMOVE_NAMESPACE_THRESHOLD_FAILURE = `${prefix}/REMOVE_NAMESPACE_THRESHOLD_FAILURE`;

export const CLEAR_ERRORS_LIST = `${prefix}/CLEAR_ERRORS_LIST`;
