/*
 *
 * NamespacesPage constants
 *
 */
const prefix = 'app/NamespacesPage';

export const INIT_ACTION = `${prefix}/INIT_ACTION`;

export const LOAD_NAMESPACES = `${prefix}/LOAD_NAMESPACES`;
export const LOAD_NAMESPACES_REQUEST = `${prefix}/LOAD_NAMESPACES_REQUEST`;
export const LOAD_NAMESPACES_SUCCESS = `${prefix}/LOAD_NAMESPACES_SUCCESS`;
export const LOAD_NAMESPACES_FAILURE = `${prefix}/LOAD_NAMESPACES_FAILURE`;

export const LOAD_NAMESPACE = `${prefix}/LOAD_NAMESPACE`;
export const LOAD_NAMESPACE_REQUEST = `${prefix}/LOAD_NAMESPACE_REQUEST`;
export const LOAD_NAMESPACE_SUCCESS = `${prefix}/LOAD_NAMESPACE_SUCCESS`;
export const LOAD_NAMESPACE_FAILURE = `${prefix}/LOAD_NAMESPACE_FAILURE`;

export const OPEN_CREATE_NAMESPACE = `${prefix}/OPEN_CREATE_NAMESPACE`;
export const CLOSE_CREATE_NAMESPACE = `${prefix}/CLOSE_CREATE_NAMESPACE`;

export const CREATE_NAMESPACE = `${prefix}/CREATE_NAMESPACE`;
export const CREATE_NAMESPACE_REQUEST = `${prefix}/CREATE_NAMESPACE_REQUEST`;
export const CREATE_NAMESPACE_SUCCESS = `${prefix}/CREATE_NAMESPACE_SUCCESS`;
export const CREATE_NAMESPACE_FAILURE = `${prefix}/CREATE_NAMESPACE_FAILURE`;

export const UPDATE_CREATE_FORM = `${prefix}/UPDATE_CREATE_FORM`;

export const REMOVE_NAMESPACE = `${prefix}/REMOVE_NAMESPACE`;
export const REMOVE_NAMESPACE_REQUEST = `${prefix}/REMOVE_NAMESPACE_REQUEST`;
export const REMOVE_NAMESPACE_SUCCESS = `${prefix}/REMOVE_NAMESPACE_SUCCESS`;
export const REMOVE_NAMESPACE_FAILURE = `${prefix}/REMOVE_NAMESPACE_FAILURE`;
