export const prefix = 'storages';

/*
  constants
*/
export const LOAD_STORAGECLASSES = `${prefix}/LOAD_STORAGECLASSES`;
export const LOAD_STORAGECLASSES_SUCCESS = `${prefix}/LOAD_STORAGECLASSES_SUCCESS`;
export const LOAD_STORAGECLASSES_FAILURE = `${prefix}/LOAD_STORAGECLASSES_FAILURE`;

export const LOAD_STORAGES = `${prefix}/LOAD_STORAGES`;
export const LOAD_STORAGES_SUCCESS = `${prefix}/LOAD_STORAGES_SUCCESS`;
export const LOAD_STORAGES_FAILURE = `${prefix}/LOAD_STORAGES_FAILURE`;

export const LOAD_NFS_STORAGES = `${prefix}/LOAD_NFS_STORAGES`;
export const LOAD_NFS_STORAGES_SUCCESS = `${prefix}/LOAD_NFS_STORAGES_SUCCESS`;
export const LOAD_NFS_STORAGES_FAILURE = `${prefix}/LOAD_NFS_STORAGES_FAILURE`;

export const LOAD_LVM_STORAGES = `${prefix}/LOAD_LVM_STORAGES`;
export const LOAD_LVM_STORAGES_SUCCESS = `${prefix}/LOAD_LVM_STORAGES_SUCCESS`;
export const LOAD_LVM_STORAGES_FAILURE = `${prefix}/LOAD_LVM_STORAGES_FAILURE`;

export const LOAD_BLOCK_DEVICES = `${prefix}/LOAD_BLOCK_DEVICES`;
export const LOAD_BLOCK_DEVICES_SUCCESS = `${prefix}/LOAD_BLOCK_DEVICES_SUCCESS`;
export const LOAD_BLOCK_DEVICES_FAILURE = `${prefix}/LOAD_BLOCK_DEVICES_FAILURE`;

export const CREATE_STORAGE = `${prefix}/CREATE_STORAGE`;
export const CREATE_STORAGE_SUCCESS = `${prefix}/CREATE_STORAGE_SUCCESS`;
export const CREATE_STORAGE_FAILURE = `${prefix}/CREATE_STORAGE_FAILURE`;

export const REMOVE_STORAGE = `${prefix}/REMOVE_STORAGE`;
export const REMOVE_STORAGE_SUCCESS = `${prefix}/REMOVE_STORAGE_SUCCESS`;
export const REMOVE_STORAGE_FAILURE = `${prefix}/REMOVE_STORAGE_FAILURE`;

export const EDIT_STORAGE = `${prefix}/EDIT_STORAGE`;
export const EDIT_STORAGE_SUCCESS = `${prefix}/EDIT_STORAGE_SUCCESS`;
export const EDIT_STORAGE_FAILURE = `${prefix}/EDIT_STORAGE_FAILURE`;
