export const prefix = 'storages';

/*
  constants
*/
export const LOAD_STORAGECLASSES = `${prefix}/LOAD_STORAGECLASSES`;
export const LOAD_STORAGECLASSES_SUCCESS = `${prefix}/LOAD_STORAGECLASSES_SUCCESS`;
export const LOAD_STORAGECLASSES_FAILURE = `${prefix}/LOAD_STORAGECLASSES_FAILURE`;

export const LOAD_STORAGES = `${prefix}/LOAD_STORAGES`;
export const LOAD_STORAGES_SUCCESS = `${prefix}/LOAD_STORAGES_SUCCESS`;
export const LOAD_STORAGES_FAILURE = `${prefix}/LOAD_STORAGES_FAILURE`;

export const LOAD_NFS_STORAGES = `${prefix}/LOAD_NFS_STORAGES`;
export const LOAD_NFS_STORAGES_SUCCESS = `${prefix}/LOAD_NFS_STORAGES_SUCCESS`;
export const LOAD_NFS_STORAGES_FAILURE = `${prefix}/LOAD_NFS_STORAGES_FAILURE`;

export const LOAD_LVM_STORAGES = `${prefix}/LOAD_LVM_STORAGES`;
export const LOAD_LVM_STORAGES_SUCCESS = `${prefix}/LOAD_LVM_STORAGES_SUCCESS`;
export const LOAD_LVM_STORAGES_FAILURE = `${prefix}/LOAD_LVM_STORAGES_FAILURE`;
