/**
 * Duck: UserQuota
 * constants: userQuota
 *
 */
export const prefix = 'userQuota';

/**
 *  constants
 */
export const LOAD_USER_QUOTA = `${prefix}/LOAD_USER_QUOTA`;
export const LOAD_USER_QUOTA_SUCCESS = `${prefix}/LOAD_USER_QUOTA_SUCCESS`;
export const LOAD_USER_QUOTA_FAILURE = `${prefix}/LOAD_USER_QUOTA_FAILURE`;

export const CREATE_USER_QUOTUM = `${prefix}/CREATE_USER_QUOTUM`;
export const CREATE_USER_QUOTUM_SUCCESS = `${prefix}/CREATE_USER_QUOTUM_SUCCESS`;
export const CREATE_USER_QUOTUM_FAILURE = `${prefix}/CREATE_USER_QUOTUM_FAILURE`;

export const UPDATE_USER_QUOTUM = `${prefix}/UPDATE_USER_QUOTUM`;
export const UPDATE_USER_QUOTUM_SUCCESS = `${prefix}/UPDATE_USER_QUOTUM_SUCCESS`;
export const UPDATE_USER_QUOTUM_FAILURE = `${prefix}/UPDATE_USER_QUOTUM_FAILURE`;

export const READ_USER_QUOTUM = `${prefix}/READ_USER_QUOTUM`;
export const READ_USER_QUOTUM_SUCCESS = `${prefix}/READ_USER_QUOTUM_SUCCESS`;
export const READ_USER_QUOTUM_FAILURE = `${prefix}/READ_USER_QUOTUM_FAILURE`;

export const REMOVE_USER_QUOTUM = `${prefix}/REMOVE_USER_QUOTUM`;
export const REMOVE_USER_QUOTUM_SUCCESS = `${prefix}/REMOVE_USER_QUOTUM_SUCCESS`;
export const REMOVE_USER_QUOTUM_FAILURE = `${prefix}/REMOVE_USER_QUOTUM_FAILURE`;

export const EXECUTE_USER_QUOTUM_ACTION = `${prefix}/EXECUTE_USER_QUOTUM_ACTION`;
export const EXECUTE_USER_QUOTUM_ACTION_SUCCESS = `${prefix}/EXECUTE_USER_QUOTUM_ACTION_SUCCESS`;
export const EXECUTE_USER_QUOTUM_ACTION_FAILURE = `${prefix}/EXECUTE_USER_QUOTUM_ACTION_FAILURE`;

export const CLEAR_ERRORS_LIST = `${prefix}/CLEAR_ERRORS_LIST`;
