/**
 * Duck: ClusterThresholds
 * constants: clusterThresholds
 *
 */
export const prefix = 'clusterThresholds';

/**
 *  constants
 */
export const LOAD_CLUSTER_THRESHOLDS = `${prefix}/LOAD_CLUSTER_THRESHOLDS`;
export const LOAD_CLUSTER_THRESHOLDS_SUCCESS = `${prefix}/LOAD_CLUSTER_THRESHOLDS_SUCCESS`;
export const LOAD_CLUSTER_THRESHOLDS_FAILURE = `${prefix}/LOAD_CLUSTER_THRESHOLDS_FAILURE`;

export const CREATE_CLUSTER_THRESHOLD = `${prefix}/CREATE_CLUSTER_THRESHOLD`;
export const CREATE_CLUSTER_THRESHOLD_SUCCESS = `${prefix}/CREATE_CLUSTER_THRESHOLD_SUCCESS`;
export const CREATE_CLUSTER_THRESHOLD_FAILURE = `${prefix}/CREATE_CLUSTER_THRESHOLD_FAILURE`;

export const UPDATE_CLUSTER_THRESHOLD = `${prefix}/UPDATE_CLUSTER_THRESHOLD`;
export const UPDATE_CLUSTER_THRESHOLD_SUCCESS = `${prefix}/UPDATE_CLUSTER_THRESHOLD_SUCCESS`;
export const UPDATE_CLUSTER_THRESHOLD_FAILURE = `${prefix}/UPDATE_CLUSTER_THRESHOLD_FAILURE`;

export const READ_CLUSTER_THRESHOLD = `${prefix}/READ_CLUSTER_THRESHOLD`;
export const READ_CLUSTER_THRESHOLD_SUCCESS = `${prefix}/READ_CLUSTER_THRESHOLD_SUCCESS`;
export const READ_CLUSTER_THRESHOLD_FAILURE = `${prefix}/READ_CLUSTER_THRESHOLD_FAILURE`;

export const REMOVE_CLUSTER_THRESHOLD = `${prefix}/REMOVE_CLUSTER_THRESHOLD`;
export const REMOVE_CLUSTER_THRESHOLD_SUCCESS = `${prefix}/REMOVE_CLUSTER_THRESHOLD_SUCCESS`;
export const REMOVE_CLUSTER_THRESHOLD_FAILURE = `${prefix}/REMOVE_CLUSTER_THRESHOLD_FAILURE`;

export const CLEAR_ERRORS_LIST = `${prefix}/CLEAR_ERRORS_LIST`;
